apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: fids-notifications
spec:
  selector:
    matchLabels:
      app: fids-notifications
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%    
  template:
    metadata:
      labels:
        app: fids-notifications
    spec:
      containers:
      - name: fids-notifications
        image: mahbnprodseaacr001.azurecr.io/fids-notification-dev:1
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 0.5
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: fids-notifications
  namespace: dev
  name: fids-notifications
  annotations: 
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"
spec:
  type: LoadBalancer
  #loadBalancerIP: 10.61.0.38
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: fids-notifications
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: fids-notifications-hpa-
  namespace: dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fids-notifications
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 60